metrics_recorder_node:
  ros__parameters:
    # !TOPICS
    clock_topic: "/clock"
    goal_reached_topic: "/smf_move_base_planner/goal_reached"
    goal_available_topic: "/goal_available"
    save_metrics_topic: "/save_metrics"
    people_collision_counter_topic: "/people_collision_counter"
    object_collision_counter_topic: "/object_collision_counter" # nodes expanded in the planner's search tree/roadmap
    num_nodes_topic: "/smf_move_base_planner/smf_num_nodes"
    agent_states_topic: "/pedsim_simulator/simulated_agents"
    odom_topic: "/odom"

    # ! measuring characteristics
    measure_rate: 10.0
    sim: True # whether the test is being done in simulation or real experiment
    robot_max_velocity: 1.0
    agent_max_velocity: 1.0
    robot_radius: 0.3
    agent_radius: 0.45

    #! saving files config
    csv_dir: "/tmp/social_nav_metrics/results"
    approach_name: "tests"
    csv_name: "new_test.csv"


collision_counter_node:
  ros__parameters:
    # !TOPICS
    odom_topic: "/odom"
    agent_states_topic: "/pedsim_simulator/simulated_agents"
    people_collision_counter_topic: "/people_collision_counter"
    object_collision_counter_topic: "/object_collision_counter"
    goal_available_topic: "/goal_available"

    # octomap service
    octomap_service: /octomap_full

    #! robot and agents params
    robot_radius: 0.3
    robot_height: 1.0
    agent_radius: 0.45
